// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0t-M0c5g3t57bZ0jVsJezbz2f5l4R8JY',
    appId: '1:1090030290233:android:b9e8388e8570c47438d4e8',
    messagingSenderId: '1090030290233',
    projectId: 'maximal-totem-276120',
    databaseURL: 'https://maximal-totem-276120-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'maximal-totem-276120.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEIZS1mAWydsJZoCYHejNU15aBek9XX1U',
    appId: '1:1090030290233:ios:9cd373551abcd04338d4e8',
    messagingSenderId: '1090030290233',
    projectId: 'maximal-totem-276120',
    databaseURL: 'https://maximal-totem-276120-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'maximal-totem-276120.appspot.com',
    iosClientId: '1090030290233-59masskkru4a1l7kfojjl8bqnkn0ckd0.apps.googleusercontent.com',
    iosBundleId: 'com.example.iyzi',
  );
}
